//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for coastalStateStandingOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coastalStateStandingOrderType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://gisis.imo.org/XML/LRIT/ddp/2008>coastalStateStandingOrderAreasIDListType">
 *       &lt;attribute name="contractingGovernmentID" use="required" type="{http://gisis.imo.org/XML/LRIT/types/2008}contractingGovernmentLRITIDType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coastalStateStandingOrderType", propOrder = {
    "value"
})
public class CoastalStateStandingOrderType {

    @XmlValue
    protected List<String> value;
    @XmlAttribute(required = true)
    protected String contractingGovernmentID;

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValue() {
        if (value == null) {
            value = new ArrayList<String>();
        }
        return this.value;
    }

    /**
     * Gets the value of the contractingGovernmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractingGovernmentID() {
        return contractingGovernmentID;
    }

    /**
     * Sets the value of the contractingGovernmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractingGovernmentID(String value) {
        this.contractingGovernmentID = value;
    }

}
