//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.imo.gisis.xml.lrit.types._2008.PolygonType;


/**
 * <p>Java class for contractingGovernmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractingGovernmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="isoCode" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}iso3166-1Alpha3CodeType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NationalPointsOfContact">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContactPoint" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contactPointType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataCentreInfo" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}dataCentreInfoType"/>
 *         &lt;element name="ASPInfo" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}aspInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SARServices">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SARService" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}sarServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ports">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Port" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PortFacilities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PortFacility" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portFacilityType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Places">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Place" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}placeType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InternalWaters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TerritorialSea">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SeawardAreaOf1000NM">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CustomCoastalAreas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="lritID" use="required" type="{http://gisis.imo.org/XML/LRIT/types/2008}contractingGovernmentLRITIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractingGovernmentType", propOrder = {
    "name",
    "nationalPointsOfContact",
    "dataCentreInfo",
    "aspInfo",
    "sarServices",
    "ports",
    "portFacilities",
    "places",
    "internalWaters",
    "territorialSea",
    "seawardAreaOf1000NM",
    "customCoastalAreas"
})
@XmlSeeAlso({
    TerritoryType.class
})
public class ContractingGovernmentType {

    @XmlElement(name = "Name", required = true)
    protected ContractingGovernmentType.Name name;
    @XmlElement(name = "NationalPointsOfContact", required = true)
    protected ContractingGovernmentType.NationalPointsOfContact nationalPointsOfContact;
    @XmlElement(name = "DataCentreInfo", required = true)
    protected DataCentreInfoType dataCentreInfo;
    @XmlElement(name = "ASPInfo")
    protected List<AspInfoType> aspInfo;
    @XmlElement(name = "SARServices", required = true)
    protected ContractingGovernmentType.SARServices sarServices;
    @XmlElement(name = "Ports", required = true)
    protected ContractingGovernmentType.Ports ports;
    @XmlElement(name = "PortFacilities", required = true)
    protected ContractingGovernmentType.PortFacilities portFacilities;
    @XmlElement(name = "Places", required = true)
    protected ContractingGovernmentType.Places places;
    @XmlElement(name = "InternalWaters", required = true)
    protected ContractingGovernmentType.InternalWaters internalWaters;
    @XmlElement(name = "TerritorialSea", required = true)
    protected ContractingGovernmentType.TerritorialSea territorialSea;
    @XmlElement(name = "SeawardAreaOf1000NM", required = true)
    protected ContractingGovernmentType.SeawardAreaOf1000NM seawardAreaOf1000NM;
    @XmlElement(name = "CustomCoastalAreas", required = true)
    protected ContractingGovernmentType.CustomCoastalAreas customCoastalAreas;
    @XmlAttribute(required = true)
    protected String lritID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.Name }
     *     
     */
    public ContractingGovernmentType.Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.Name }
     *     
     */
    public void setName(ContractingGovernmentType.Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the nationalPointsOfContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.NationalPointsOfContact }
     *     
     */
    public ContractingGovernmentType.NationalPointsOfContact getNationalPointsOfContact() {
        return nationalPointsOfContact;
    }

    /**
     * Sets the value of the nationalPointsOfContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.NationalPointsOfContact }
     *     
     */
    public void setNationalPointsOfContact(ContractingGovernmentType.NationalPointsOfContact value) {
        this.nationalPointsOfContact = value;
    }

    /**
     * Gets the value of the dataCentreInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DataCentreInfoType }
     *     
     */
    public DataCentreInfoType getDataCentreInfo() {
        return dataCentreInfo;
    }

    /**
     * Sets the value of the dataCentreInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCentreInfoType }
     *     
     */
    public void setDataCentreInfo(DataCentreInfoType value) {
        this.dataCentreInfo = value;
    }

    /**
     * Gets the value of the aspInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aspInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getASPInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AspInfoType }
     * 
     * 
     */
    public List<AspInfoType> getASPInfo() {
        if (aspInfo == null) {
            aspInfo = new ArrayList<AspInfoType>();
        }
        return this.aspInfo;
    }

    /**
     * Gets the value of the sarServices property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.SARServices }
     *     
     */
    public ContractingGovernmentType.SARServices getSARServices() {
        return sarServices;
    }

    /**
     * Sets the value of the sarServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.SARServices }
     *     
     */
    public void setSARServices(ContractingGovernmentType.SARServices value) {
        this.sarServices = value;
    }

    /**
     * Gets the value of the ports property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.Ports }
     *     
     */
    public ContractingGovernmentType.Ports getPorts() {
        return ports;
    }

    /**
     * Sets the value of the ports property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.Ports }
     *     
     */
    public void setPorts(ContractingGovernmentType.Ports value) {
        this.ports = value;
    }

    /**
     * Gets the value of the portFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.PortFacilities }
     *     
     */
    public ContractingGovernmentType.PortFacilities getPortFacilities() {
        return portFacilities;
    }

    /**
     * Sets the value of the portFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.PortFacilities }
     *     
     */
    public void setPortFacilities(ContractingGovernmentType.PortFacilities value) {
        this.portFacilities = value;
    }

    /**
     * Gets the value of the places property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.Places }
     *     
     */
    public ContractingGovernmentType.Places getPlaces() {
        return places;
    }

    /**
     * Sets the value of the places property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.Places }
     *     
     */
    public void setPlaces(ContractingGovernmentType.Places value) {
        this.places = value;
    }

    /**
     * Gets the value of the internalWaters property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.InternalWaters }
     *     
     */
    public ContractingGovernmentType.InternalWaters getInternalWaters() {
        return internalWaters;
    }

    /**
     * Sets the value of the internalWaters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.InternalWaters }
     *     
     */
    public void setInternalWaters(ContractingGovernmentType.InternalWaters value) {
        this.internalWaters = value;
    }

    /**
     * Gets the value of the territorialSea property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.TerritorialSea }
     *     
     */
    public ContractingGovernmentType.TerritorialSea getTerritorialSea() {
        return territorialSea;
    }

    /**
     * Sets the value of the territorialSea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.TerritorialSea }
     *     
     */
    public void setTerritorialSea(ContractingGovernmentType.TerritorialSea value) {
        this.territorialSea = value;
    }

    /**
     * Gets the value of the seawardAreaOf1000NM property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.SeawardAreaOf1000NM }
     *     
     */
    public ContractingGovernmentType.SeawardAreaOf1000NM getSeawardAreaOf1000NM() {
        return seawardAreaOf1000NM;
    }

    /**
     * Sets the value of the seawardAreaOf1000NM property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.SeawardAreaOf1000NM }
     *     
     */
    public void setSeawardAreaOf1000NM(ContractingGovernmentType.SeawardAreaOf1000NM value) {
        this.seawardAreaOf1000NM = value;
    }

    /**
     * Gets the value of the customCoastalAreas property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType.CustomCoastalAreas }
     *     
     */
    public ContractingGovernmentType.CustomCoastalAreas getCustomCoastalAreas() {
        return customCoastalAreas;
    }

    /**
     * Sets the value of the customCoastalAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType.CustomCoastalAreas }
     *     
     */
    public void setCustomCoastalAreas(ContractingGovernmentType.CustomCoastalAreas value) {
        this.customCoastalAreas = value;
    }

    /**
     * Gets the value of the lritID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLritID() {
        return lritID;
    }

    /**
     * Sets the value of the lritID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLritID(String value) {
        this.lritID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polygon"
    })
    public static class CustomCoastalAreas {

        @XmlElement(name = "Polygon")
        protected List<PolygonType> polygon;

        /**
         * Gets the value of the polygon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polygon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolygon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PolygonType }
         * 
         * 
         */
        public List<PolygonType> getPolygon() {
            if (polygon == null) {
                polygon = new ArrayList<PolygonType>();
            }
            return this.polygon;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polygon"
    })
    public static class InternalWaters {

        @XmlElement(name = "Polygon")
        protected List<PolygonType> polygon;

        /**
         * Gets the value of the polygon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polygon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolygon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PolygonType }
         * 
         * 
         */
        public List<PolygonType> getPolygon() {
            if (polygon == null) {
                polygon = new ArrayList<PolygonType>();
            }
            return this.polygon;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="isoCode" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}iso3166-1Alpha3CodeType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Name {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String isoCode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the isoCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsoCode() {
            return isoCode;
        }

        /**
         * Sets the value of the isoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsoCode(String value) {
            this.isoCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContactPoint" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contactPointType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactPoint"
    })
    public static class NationalPointsOfContact {

        @XmlElement(name = "ContactPoint")
        protected List<ContactPointType> contactPoint;

        /**
         * Gets the value of the contactPoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contactPoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContactPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ContactPointType }
         * 
         * 
         */
        public List<ContactPointType> getContactPoint() {
            if (contactPoint == null) {
                contactPoint = new ArrayList<ContactPointType>();
            }
            return this.contactPoint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Place" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}placeType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "place"
    })
    public static class Places {

        @XmlElement(name = "Place")
        protected List<PlaceType> place;

        /**
         * Gets the value of the place property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the place property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlaceType }
         * 
         * 
         */
        public List<PlaceType> getPlace() {
            if (place == null) {
                place = new ArrayList<PlaceType>();
            }
            return this.place;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PortFacility" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portFacilityType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "portFacility"
    })
    public static class PortFacilities {

        @XmlElement(name = "PortFacility")
        protected List<PortFacilityType> portFacility;

        /**
         * Gets the value of the portFacility property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the portFacility property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPortFacility().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PortFacilityType }
         * 
         * 
         */
        public List<PortFacilityType> getPortFacility() {
            if (portFacility == null) {
                portFacility = new ArrayList<PortFacilityType>();
            }
            return this.portFacility;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Port" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "port"
    })
    public static class Ports {

        @XmlElement(name = "Port")
        protected List<PortType> port;

        /**
         * Gets the value of the port property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the port property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPort().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PortType }
         * 
         * 
         */
        public List<PortType> getPort() {
            if (port == null) {
                port = new ArrayList<PortType>();
            }
            return this.port;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SARService" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}sarServiceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sarService"
    })
    public static class SARServices {

        @XmlElement(name = "SARService")
        protected List<SarServiceType> sarService;

        /**
         * Gets the value of the sarService property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sarService property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSARService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SarServiceType }
         * 
         * 
         */
        public List<SarServiceType> getSARService() {
            if (sarService == null) {
                sarService = new ArrayList<SarServiceType>();
            }
            return this.sarService;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polygon"
    })
    public static class SeawardAreaOf1000NM {

        @XmlElement(name = "Polygon")
        protected List<PolygonType> polygon;

        /**
         * Gets the value of the polygon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polygon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolygon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PolygonType }
         * 
         * 
         */
        public List<PolygonType> getPolygon() {
            if (polygon == null) {
                polygon = new ArrayList<PolygonType>();
            }
            return this.polygon;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polygon"
    })
    public static class TerritorialSea {

        @XmlElement(name = "Polygon")
        protected List<PolygonType> polygon;

        /**
         * Gets the value of the polygon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polygon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolygon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PolygonType }
         * 
         * 
         */
        public List<PolygonType> getPolygon() {
            if (polygon == null) {
                polygon = new ArrayList<PolygonType>();
            }
            return this.polygon;
        }

    }

}
