//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Regular" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Delete" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
 *                   &lt;element name="Insert" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
 *                   &lt;element name="Update" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="baseRegularVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="targetRegularVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="targetPublishedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="targetImplementationAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Immediate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Delete" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
 *                   &lt;element name="Insert" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
 *                   &lt;element name="Update" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="baseImmediateVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="targetImmediateVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="targetPublishedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="targetImplementationAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="baseRegularVersionNum" type="{http://gisis.imo.org/XML/LRIT/types/2008}ddpIncrementalVersionNumType" />
 *       &lt;attribute name="targetRegularVersionNum" type="{http://gisis.imo.org/XML/LRIT/types/2008}ddpIncrementalVersionNumType" />
 *       &lt;attribute name="baseImmediateVersionNum" type="{http://gisis.imo.org/XML/LRIT/types/2008}ddpIncrementalVersionNumType" />
 *       &lt;attribute name="targetImmediateVersionNum" type="{http://gisis.imo.org/XML/LRIT/types/2008}ddpIncrementalVersionNumType" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regular",
    "immediate"
})
@XmlRootElement(name = "DataDistributionPlan-IncrementalUpdate")
public class DataDistributionPlanIncrementalUpdate {

    @XmlElement(name = "Regular")
    protected List<DataDistributionPlanIncrementalUpdate.Regular> regular;
    @XmlElement(name = "Immediate")
    protected List<DataDistributionPlanIncrementalUpdate.Immediate> immediate;
    @XmlAttribute
    protected String baseRegularVersionNum;
    @XmlAttribute
    protected String targetRegularVersionNum;
    @XmlAttribute
    protected String baseImmediateVersionNum;
    @XmlAttribute
    protected String targetImmediateVersionNum;
    @XmlAttribute(required = true)
    protected BigDecimal schemaVersion;

    /**
     * Gets the value of the regular property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regular property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegular().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataDistributionPlanIncrementalUpdate.Regular }
     * 
     * 
     */
    public List<DataDistributionPlanIncrementalUpdate.Regular> getRegular() {
        if (regular == null) {
            regular = new ArrayList<DataDistributionPlanIncrementalUpdate.Regular>();
        }
        return this.regular;
    }

    /**
     * Gets the value of the immediate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immediate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImmediate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataDistributionPlanIncrementalUpdate.Immediate }
     * 
     * 
     */
    public List<DataDistributionPlanIncrementalUpdate.Immediate> getImmediate() {
        if (immediate == null) {
            immediate = new ArrayList<DataDistributionPlanIncrementalUpdate.Immediate>();
        }
        return this.immediate;
    }

    /**
     * Gets the value of the baseRegularVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRegularVersionNum() {
        return baseRegularVersionNum;
    }

    /**
     * Sets the value of the baseRegularVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRegularVersionNum(String value) {
        this.baseRegularVersionNum = value;
    }

    /**
     * Gets the value of the targetRegularVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetRegularVersionNum() {
        return targetRegularVersionNum;
    }

    /**
     * Sets the value of the targetRegularVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetRegularVersionNum(String value) {
        this.targetRegularVersionNum = value;
    }

    /**
     * Gets the value of the baseImmediateVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseImmediateVersionNum() {
        return baseImmediateVersionNum;
    }

    /**
     * Sets the value of the baseImmediateVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseImmediateVersionNum(String value) {
        this.baseImmediateVersionNum = value;
    }

    /**
     * Gets the value of the targetImmediateVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetImmediateVersionNum() {
        return targetImmediateVersionNum;
    }

    /**
     * Sets the value of the targetImmediateVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetImmediateVersionNum(String value) {
        this.targetImmediateVersionNum = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSchemaVersion(BigDecimal value) {
        this.schemaVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Delete" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
     *         &lt;element name="Insert" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
     *         &lt;element name="Update" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}immediateIncrementableType"/>
     *       &lt;/choice>
     *       &lt;attribute name="baseImmediateVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="targetImmediateVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="targetPublishedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="targetImplementationAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deleteOrInsertOrUpdate"
    })
    public static class Immediate {

        @XmlElementRefs({
            @XmlElementRef(name = "Insert", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class),
            @XmlElementRef(name = "Update", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class),
            @XmlElementRef(name = "Delete", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class)
        })
        protected List<JAXBElement<ImmediateIncrementableType>> deleteOrInsertOrUpdate;
        @XmlAttribute(required = true)
        protected int baseImmediateVersionNum;
        @XmlAttribute(required = true)
        protected int targetImmediateVersionNum;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar targetPublishedAt;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar targetImplementationAt;

        /**
         * Gets the value of the deleteOrInsertOrUpdate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deleteOrInsertOrUpdate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeleteOrInsertOrUpdate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}
         * {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}
         * {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<ImmediateIncrementableType>> getDeleteOrInsertOrUpdate() {
            if (deleteOrInsertOrUpdate == null) {
                deleteOrInsertOrUpdate = new ArrayList<JAXBElement<ImmediateIncrementableType>>();
            }
            return this.deleteOrInsertOrUpdate;
        }

        /**
         * Gets the value of the baseImmediateVersionNum property.
         * 
         */
        public int getBaseImmediateVersionNum() {
            return baseImmediateVersionNum;
        }

        /**
         * Sets the value of the baseImmediateVersionNum property.
         * 
         */
        public void setBaseImmediateVersionNum(int value) {
            this.baseImmediateVersionNum = value;
        }

        /**
         * Gets the value of the targetImmediateVersionNum property.
         * 
         */
        public int getTargetImmediateVersionNum() {
            return targetImmediateVersionNum;
        }

        /**
         * Sets the value of the targetImmediateVersionNum property.
         * 
         */
        public void setTargetImmediateVersionNum(int value) {
            this.targetImmediateVersionNum = value;
        }

        /**
         * Gets the value of the targetPublishedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTargetPublishedAt() {
            return targetPublishedAt;
        }

        /**
         * Sets the value of the targetPublishedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTargetPublishedAt(XMLGregorianCalendar value) {
            this.targetPublishedAt = value;
        }

        /**
         * Gets the value of the targetImplementationAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTargetImplementationAt() {
            return targetImplementationAt;
        }

        /**
         * Sets the value of the targetImplementationAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTargetImplementationAt(XMLGregorianCalendar value) {
            this.targetImplementationAt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Delete" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
     *         &lt;element name="Insert" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
     *         &lt;element name="Update" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}regularIncrementableType"/>
     *       &lt;/choice>
     *       &lt;attribute name="baseRegularVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="targetRegularVersionNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="targetPublishedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="targetImplementationAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deleteOrInsertOrUpdate"
    })
    public static class Regular {

        @XmlElementRefs({
            @XmlElementRef(name = "Update", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class),
            @XmlElementRef(name = "Insert", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class),
            @XmlElementRef(name = "Delete", namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", type = JAXBElement.class)
        })
        protected List<JAXBElement<RegularIncrementableType>> deleteOrInsertOrUpdate;
        @XmlAttribute(required = true)
        protected int baseRegularVersionNum;
        @XmlAttribute(required = true)
        protected int targetRegularVersionNum;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar targetPublishedAt;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar targetImplementationAt;

        /**
         * Gets the value of the deleteOrInsertOrUpdate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deleteOrInsertOrUpdate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeleteOrInsertOrUpdate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}
         * {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}
         * {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<RegularIncrementableType>> getDeleteOrInsertOrUpdate() {
            if (deleteOrInsertOrUpdate == null) {
                deleteOrInsertOrUpdate = new ArrayList<JAXBElement<RegularIncrementableType>>();
            }
            return this.deleteOrInsertOrUpdate;
        }

        /**
         * Gets the value of the baseRegularVersionNum property.
         * 
         */
        public int getBaseRegularVersionNum() {
            return baseRegularVersionNum;
        }

        /**
         * Sets the value of the baseRegularVersionNum property.
         * 
         */
        public void setBaseRegularVersionNum(int value) {
            this.baseRegularVersionNum = value;
        }

        /**
         * Gets the value of the targetRegularVersionNum property.
         * 
         */
        public int getTargetRegularVersionNum() {
            return targetRegularVersionNum;
        }

        /**
         * Sets the value of the targetRegularVersionNum property.
         * 
         */
        public void setTargetRegularVersionNum(int value) {
            this.targetRegularVersionNum = value;
        }

        /**
         * Gets the value of the targetPublishedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTargetPublishedAt() {
            return targetPublishedAt;
        }

        /**
         * Sets the value of the targetPublishedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTargetPublishedAt(XMLGregorianCalendar value) {
            this.targetPublishedAt = value;
        }

        /**
         * Gets the value of the targetImplementationAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTargetImplementationAt() {
            return targetImplementationAt;
        }

        /**
         * Sets the value of the targetImplementationAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTargetImplementationAt(XMLGregorianCalendar value) {
            this.targetImplementationAt = value;
        }

    }

}
