//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for exclusionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exclusionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExcludedContractingGovernmentID" type="{http://gisis.imo.org/XML/LRIT/types/2008}contractingGovernmentLRITIDType"/>
 *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Until" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="contractingGovernmentID" use="required" type="{http://gisis.imo.org/XML/LRIT/types/2008}contractingGovernmentLRITIDType" />
 *       &lt;attribute name="exclusionID" use="required" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}exclusionIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exclusionType", propOrder = {
    "excludedContractingGovernmentID",
    "from",
    "until",
    "reason"
})
public class ExclusionType {

    @XmlElement(name = "ExcludedContractingGovernmentID", required = true)
    protected String excludedContractingGovernmentID;
    @XmlElement(name = "From")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar from;
    @XmlElement(name = "Until")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar until;
    @XmlElement(name = "Reason")
    protected String reason;
    @XmlAttribute(required = true)
    protected String contractingGovernmentID;
    @XmlAttribute(required = true)
    protected String exclusionID;

    /**
     * Gets the value of the excludedContractingGovernmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludedContractingGovernmentID() {
        return excludedContractingGovernmentID;
    }

    /**
     * Sets the value of the excludedContractingGovernmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludedContractingGovernmentID(String value) {
        this.excludedContractingGovernmentID = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFrom(XMLGregorianCalendar value) {
        this.from = value;
    }

    /**
     * Gets the value of the until property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUntil() {
        return until;
    }

    /**
     * Sets the value of the until property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUntil(XMLGregorianCalendar value) {
        this.until = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the contractingGovernmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractingGovernmentID() {
        return contractingGovernmentID;
    }

    /**
     * Sets the value of the contractingGovernmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractingGovernmentID(String value) {
        this.contractingGovernmentID = value;
    }

    /**
     * Gets the value of the exclusionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExclusionID() {
        return exclusionID;
    }

    /**
     * Sets the value of the exclusionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExclusionID(String value) {
        this.exclusionID = value;
    }

}
