//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ideType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ideType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DCInterfaceWebServiceLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="DDPInterfaceWebServiceLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="ContactPoint" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contactPointType" maxOccurs="unbounded"/>
 *         &lt;element name="AdditionalInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lritID" type="{http://gisis.imo.org/XML/LRIT/types/2008}ideLRITIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ideType", propOrder = {
    "name",
    "dcInterfaceWebServiceLocation",
    "ddpInterfaceWebServiceLocation",
    "contactPoint",
    "additionalInformation"
})
public class IdeType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "DCInterfaceWebServiceLocation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String dcInterfaceWebServiceLocation;
    @XmlElement(name = "DDPInterfaceWebServiceLocation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String ddpInterfaceWebServiceLocation;
    @XmlElement(name = "ContactPoint", required = true)
    protected List<ContactPointType> contactPoint;
    @XmlElement(name = "AdditionalInformation")
    protected String additionalInformation;
    @XmlAttribute
    protected String lritID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dcInterfaceWebServiceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCInterfaceWebServiceLocation() {
        return dcInterfaceWebServiceLocation;
    }

    /**
     * Sets the value of the dcInterfaceWebServiceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCInterfaceWebServiceLocation(String value) {
        this.dcInterfaceWebServiceLocation = value;
    }

    /**
     * Gets the value of the ddpInterfaceWebServiceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDPInterfaceWebServiceLocation() {
        return ddpInterfaceWebServiceLocation;
    }

    /**
     * Sets the value of the ddpInterfaceWebServiceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDPInterfaceWebServiceLocation(String value) {
        this.ddpInterfaceWebServiceLocation = value;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactPointType }
     * 
     * 
     */
    public List<ContactPointType> getContactPoint() {
        if (contactPoint == null) {
            contactPoint = new ArrayList<ContactPointType>();
        }
        return this.contactPoint;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInformation(String value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the lritID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLritID() {
        return lritID;
    }

    /**
     * Sets the value of the lritID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLritID(String value) {
        this.lritID = value;
    }

}
