//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for immediateIncrementableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="immediateIncrementableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="StandingOrder" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}coastalStateStandingOrderType"/>
 *         &lt;element name="Exclusion" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}exclusionType"/>
 *         &lt;element name="DataCentre" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}dataCentreType"/>
 *         &lt;element name="DDPServer" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}ddpServerType"/>
 *         &lt;element name="IDE" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}ideType"/>
 *       &lt;/choice>
 *       &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "immediateIncrementableType", propOrder = {
    "standingOrder",
    "exclusion",
    "dataCentre",
    "ddpServer",
    "ide"
})
public class ImmediateIncrementableType {

    @XmlElement(name = "StandingOrder")
    protected CoastalStateStandingOrderType standingOrder;
    @XmlElement(name = "Exclusion")
    protected ExclusionType exclusion;
    @XmlElement(name = "DataCentre")
    protected DataCentreType dataCentre;
    @XmlElement(name = "DDPServer")
    protected DdpServerType ddpServer;
    @XmlElement(name = "IDE")
    protected IdeType ide;
    @XmlAttribute(required = true)
    protected String xPath;

    /**
     * Gets the value of the standingOrder property.
     * 
     * @return
     *     possible object is
     *     {@link CoastalStateStandingOrderType }
     *     
     */
    public CoastalStateStandingOrderType getStandingOrder() {
        return standingOrder;
    }

    /**
     * Sets the value of the standingOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoastalStateStandingOrderType }
     *     
     */
    public void setStandingOrder(CoastalStateStandingOrderType value) {
        this.standingOrder = value;
    }

    /**
     * Gets the value of the exclusion property.
     * 
     * @return
     *     possible object is
     *     {@link ExclusionType }
     *     
     */
    public ExclusionType getExclusion() {
        return exclusion;
    }

    /**
     * Sets the value of the exclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExclusionType }
     *     
     */
    public void setExclusion(ExclusionType value) {
        this.exclusion = value;
    }

    /**
     * Gets the value of the dataCentre property.
     * 
     * @return
     *     possible object is
     *     {@link DataCentreType }
     *     
     */
    public DataCentreType getDataCentre() {
        return dataCentre;
    }

    /**
     * Sets the value of the dataCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCentreType }
     *     
     */
    public void setDataCentre(DataCentreType value) {
        this.dataCentre = value;
    }

    /**
     * Gets the value of the ddpServer property.
     * 
     * @return
     *     possible object is
     *     {@link DdpServerType }
     *     
     */
    public DdpServerType getDDPServer() {
        return ddpServer;
    }

    /**
     * Sets the value of the ddpServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DdpServerType }
     *     
     */
    public void setDDPServer(DdpServerType value) {
        this.ddpServer = value;
    }

    /**
     * Gets the value of the ide property.
     * 
     * @return
     *     possible object is
     *     {@link IdeType }
     *     
     */
    public IdeType getIDE() {
        return ide;
    }

    /**
     * Sets the value of the ide property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdeType }
     *     
     */
    public void setIDE(IdeType value) {
        this.ide = value;
    }

    /**
     * Gets the value of the xPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPath() {
        return xPath;
    }

    /**
     * Sets the value of the xPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPath(String value) {
        this.xPath = value;
    }

}
