//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imo.gisis.xml.lrit.ddp._2008 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataDistributionPlanIncrementalUpdateRegularUpdate_QNAME = new QName("http://gisis.imo.org/XML/LRIT/ddp/2008", "Update");
    private final static QName _DataDistributionPlanIncrementalUpdateRegularInsert_QNAME = new QName("http://gisis.imo.org/XML/LRIT/ddp/2008", "Insert");
    private final static QName _DataDistributionPlanIncrementalUpdateRegularDelete_QNAME = new QName("http://gisis.imo.org/XML/LRIT/ddp/2008", "Delete");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imo.gisis.xml.lrit.ddp._2008
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.Ports }
     * 
     */
    public ContractingGovernmentType.Ports createContractingGovernmentTypePorts() {
        return new ContractingGovernmentType.Ports();
    }

    /**
     * Create an instance of {@link DataDistributionPlan.CoastalStateStandingOrders }
     * 
     */
    public DataDistributionPlan.CoastalStateStandingOrders createDataDistributionPlanCoastalStateStandingOrders() {
        return new DataDistributionPlan.CoastalStateStandingOrders();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.SARServices }
     * 
     */
    public ContractingGovernmentType.SARServices createContractingGovernmentTypeSARServices() {
        return new ContractingGovernmentType.SARServices();
    }

    /**
     * Create an instance of {@link SarServiceType }
     * 
     */
    public SarServiceType createSarServiceType() {
        return new SarServiceType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.Name }
     * 
     */
    public ContractingGovernmentType.Name createContractingGovernmentTypeName() {
        return new ContractingGovernmentType.Name();
    }

    /**
     * Create an instance of {@link DataDistributionPlanIncrementalUpdate.Immediate }
     * 
     */
    public DataDistributionPlanIncrementalUpdate.Immediate createDataDistributionPlanIncrementalUpdateImmediate() {
        return new DataDistributionPlanIncrementalUpdate.Immediate();
    }

    /**
     * Create an instance of {@link ExclusionType }
     * 
     */
    public ExclusionType createExclusionType() {
        return new ExclusionType();
    }

    /**
     * Create an instance of {@link DataDistributionPlanIncrementalUpdate.Regular }
     * 
     */
    public DataDistributionPlanIncrementalUpdate.Regular createDataDistributionPlanIncrementalUpdateRegular() {
        return new DataDistributionPlanIncrementalUpdate.Regular();
    }

    /**
     * Create an instance of {@link ImmediateIncrementableType }
     * 
     */
    public ImmediateIncrementableType createImmediateIncrementableType() {
        return new ImmediateIncrementableType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.Places }
     * 
     */
    public ContractingGovernmentType.Places createContractingGovernmentTypePlaces() {
        return new ContractingGovernmentType.Places();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.PortFacilities }
     * 
     */
    public ContractingGovernmentType.PortFacilities createContractingGovernmentTypePortFacilities() {
        return new ContractingGovernmentType.PortFacilities();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.CustomCoastalAreas }
     * 
     */
    public ContractingGovernmentType.CustomCoastalAreas createContractingGovernmentTypeCustomCoastalAreas() {
        return new ContractingGovernmentType.CustomCoastalAreas();
    }

    /**
     * Create an instance of {@link DataDistributionPlan.Exclusions }
     * 
     */
    public DataDistributionPlan.Exclusions createDataDistributionPlanExclusions() {
        return new DataDistributionPlan.Exclusions();
    }

    /**
     * Create an instance of {@link DataDistributionPlan.ASPs }
     * 
     */
    public DataDistributionPlan.ASPs createDataDistributionPlanASPs() {
        return new DataDistributionPlan.ASPs();
    }

    /**
     * Create an instance of {@link DataDistributionPlan }
     * 
     */
    public DataDistributionPlan createDataDistributionPlan() {
        return new DataDistributionPlan();
    }

    /**
     * Create an instance of {@link DataCentreInfoType }
     * 
     */
    public DataCentreInfoType createDataCentreInfoType() {
        return new DataCentreInfoType();
    }

    /**
     * Create an instance of {@link DataDistributionPlanIncrementalUpdate }
     * 
     */
    public DataDistributionPlanIncrementalUpdate createDataDistributionPlanIncrementalUpdate() {
        return new DataDistributionPlanIncrementalUpdate();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.SeawardAreaOf1000NM }
     * 
     */
    public ContractingGovernmentType.SeawardAreaOf1000NM createContractingGovernmentTypeSeawardAreaOf1000NM() {
        return new ContractingGovernmentType.SeawardAreaOf1000NM();
    }

    /**
     * Create an instance of {@link CoastalStateStandingOrderType }
     * 
     */
    public CoastalStateStandingOrderType createCoastalStateStandingOrderType() {
        return new CoastalStateStandingOrderType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.TerritorialSea }
     * 
     */
    public ContractingGovernmentType.TerritorialSea createContractingGovernmentTypeTerritorialSea() {
        return new ContractingGovernmentType.TerritorialSea();
    }

    /**
     * Create an instance of {@link DataDistributionPlan.DataCentres }
     * 
     */
    public DataDistributionPlan.DataCentres createDataDistributionPlanDataCentres() {
        return new DataDistributionPlan.DataCentres();
    }

    /**
     * Create an instance of {@link RegularIncrementableType }
     * 
     */
    public RegularIncrementableType createRegularIncrementableType() {
        return new RegularIncrementableType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.NationalPointsOfContact }
     * 
     */
    public ContractingGovernmentType.NationalPointsOfContact createContractingGovernmentTypeNationalPointsOfContact() {
        return new ContractingGovernmentType.NationalPointsOfContact();
    }

    /**
     * Create an instance of {@link PortType }
     * 
     */
    public PortType createPortType() {
        return new PortType();
    }

    /**
     * Create an instance of {@link DataCentreType }
     * 
     */
    public DataCentreType createDataCentreType() {
        return new DataCentreType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType.InternalWaters }
     * 
     */
    public ContractingGovernmentType.InternalWaters createContractingGovernmentTypeInternalWaters() {
        return new ContractingGovernmentType.InternalWaters();
    }

    /**
     * Create an instance of {@link TerritoryType }
     * 
     */
    public TerritoryType createTerritoryType() {
        return new TerritoryType();
    }

    /**
     * Create an instance of {@link DdpServerType }
     * 
     */
    public DdpServerType createDdpServerType() {
        return new DdpServerType();
    }

    /**
     * Create an instance of {@link PortFacilityType }
     * 
     */
    public PortFacilityType createPortFacilityType() {
        return new PortFacilityType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link IdeType }
     * 
     */
    public IdeType createIdeType() {
        return new IdeType();
    }

    /**
     * Create an instance of {@link ContactPointType }
     * 
     */
    public ContactPointType createContactPointType() {
        return new ContactPointType();
    }

    /**
     * Create an instance of {@link ContractingGovernmentType }
     * 
     */
    public ContractingGovernmentType createContractingGovernmentType() {
        return new ContractingGovernmentType();
    }

    /**
     * Create an instance of {@link LritCoordinatorType }
     * 
     */
    public LritCoordinatorType createLritCoordinatorType() {
        return new LritCoordinatorType();
    }

    /**
     * Create an instance of {@link AspInfoType }
     * 
     */
    public AspInfoType createAspInfoType() {
        return new AspInfoType();
    }

    /**
     * Create an instance of {@link AspType }
     * 
     */
    public AspType createAspType() {
        return new AspType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Update", scope = DataDistributionPlanIncrementalUpdate.Regular.class)
    public JAXBElement<RegularIncrementableType> createDataDistributionPlanIncrementalUpdateRegularUpdate(RegularIncrementableType value) {
        return new JAXBElement<RegularIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularUpdate_QNAME, RegularIncrementableType.class, DataDistributionPlanIncrementalUpdate.Regular.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Insert", scope = DataDistributionPlanIncrementalUpdate.Regular.class)
    public JAXBElement<RegularIncrementableType> createDataDistributionPlanIncrementalUpdateRegularInsert(RegularIncrementableType value) {
        return new JAXBElement<RegularIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularInsert_QNAME, RegularIncrementableType.class, DataDistributionPlanIncrementalUpdate.Regular.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegularIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Delete", scope = DataDistributionPlanIncrementalUpdate.Regular.class)
    public JAXBElement<RegularIncrementableType> createDataDistributionPlanIncrementalUpdateRegularDelete(RegularIncrementableType value) {
        return new JAXBElement<RegularIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularDelete_QNAME, RegularIncrementableType.class, DataDistributionPlanIncrementalUpdate.Regular.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Update", scope = DataDistributionPlanIncrementalUpdate.Immediate.class)
    public JAXBElement<ImmediateIncrementableType> createDataDistributionPlanIncrementalUpdateImmediateUpdate(ImmediateIncrementableType value) {
        return new JAXBElement<ImmediateIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularUpdate_QNAME, ImmediateIncrementableType.class, DataDistributionPlanIncrementalUpdate.Immediate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Insert", scope = DataDistributionPlanIncrementalUpdate.Immediate.class)
    public JAXBElement<ImmediateIncrementableType> createDataDistributionPlanIncrementalUpdateImmediateInsert(ImmediateIncrementableType value) {
        return new JAXBElement<ImmediateIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularInsert_QNAME, ImmediateIncrementableType.class, DataDistributionPlanIncrementalUpdate.Immediate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImmediateIncrementableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gisis.imo.org/XML/LRIT/ddp/2008", name = "Delete", scope = DataDistributionPlanIncrementalUpdate.Immediate.class)
    public JAXBElement<ImmediateIncrementableType> createDataDistributionPlanIncrementalUpdateImmediateDelete(ImmediateIncrementableType value) {
        return new JAXBElement<ImmediateIncrementableType>(_DataDistributionPlanIncrementalUpdateRegularDelete_QNAME, ImmediateIncrementableType.class, DataDistributionPlanIncrementalUpdate.Immediate.class, value);
    }

}
