//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.imo.gisis.xml.lrit.types._2008.PolygonType;


/**
 * <p>Java class for regularIncrementableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regularIncrementableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ContractingGovernment" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contractingGovernmentType"/>
 *         &lt;element name="Territory" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}territoryType"/>
 *         &lt;element name="ContactPoint" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contactPointType"/>
 *         &lt;element name="ASPInfo" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}aspInfoType"/>
 *         &lt;element name="SARService" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}sarServiceType"/>
 *         &lt;element name="Port" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portType"/>
 *         &lt;element name="PortFacility" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}portFacilityType"/>
 *         &lt;element name="Place" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}placeType"/>
 *         &lt;element name="Polygon" type="{http://gisis.imo.org/XML/LRIT/types/2008}polygonType"/>
 *         &lt;element name="DataCentreInfo" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}dataCentreInfoType"/>
 *         &lt;element name="ASP" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}aspType"/>
 *         &lt;element name="LRITCoordinator" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}lritCoordinatorType"/>
 *       &lt;/choice>
 *       &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regularIncrementableType", propOrder = {
    "contractingGovernment",
    "territory",
    "contactPoint",
    "aspInfo",
    "sarService",
    "port",
    "portFacility",
    "place",
    "polygon",
    "dataCentreInfo",
    "asp",
    "lritCoordinator"
})
public class RegularIncrementableType {

    @XmlElement(name = "ContractingGovernment")
    protected ContractingGovernmentType contractingGovernment;
    @XmlElement(name = "Territory")
    protected TerritoryType territory;
    @XmlElement(name = "ContactPoint")
    protected ContactPointType contactPoint;
    @XmlElement(name = "ASPInfo")
    protected AspInfoType aspInfo;
    @XmlElement(name = "SARService")
    protected SarServiceType sarService;
    @XmlElement(name = "Port")
    protected PortType port;
    @XmlElement(name = "PortFacility")
    protected PortFacilityType portFacility;
    @XmlElement(name = "Place")
    protected PlaceType place;
    @XmlElement(name = "Polygon")
    protected PolygonType polygon;
    @XmlElement(name = "DataCentreInfo")
    protected DataCentreInfoType dataCentreInfo;
    @XmlElement(name = "ASP")
    protected AspType asp;
    @XmlElement(name = "LRITCoordinator")
    protected LritCoordinatorType lritCoordinator;
    @XmlAttribute(required = true)
    protected String xPath;

    /**
     * Gets the value of the contractingGovernment property.
     * 
     * @return
     *     possible object is
     *     {@link ContractingGovernmentType }
     *     
     */
    public ContractingGovernmentType getContractingGovernment() {
        return contractingGovernment;
    }

    /**
     * Sets the value of the contractingGovernment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractingGovernmentType }
     *     
     */
    public void setContractingGovernment(ContractingGovernmentType value) {
        this.contractingGovernment = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * @return
     *     possible object is
     *     {@link TerritoryType }
     *     
     */
    public TerritoryType getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerritoryType }
     *     
     */
    public void setTerritory(TerritoryType value) {
        this.territory = value;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPointType }
     *     
     */
    public ContactPointType getContactPoint() {
        return contactPoint;
    }

    /**
     * Sets the value of the contactPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPointType }
     *     
     */
    public void setContactPoint(ContactPointType value) {
        this.contactPoint = value;
    }

    /**
     * Gets the value of the aspInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AspInfoType }
     *     
     */
    public AspInfoType getASPInfo() {
        return aspInfo;
    }

    /**
     * Sets the value of the aspInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspInfoType }
     *     
     */
    public void setASPInfo(AspInfoType value) {
        this.aspInfo = value;
    }

    /**
     * Gets the value of the sarService property.
     * 
     * @return
     *     possible object is
     *     {@link SarServiceType }
     *     
     */
    public SarServiceType getSARService() {
        return sarService;
    }

    /**
     * Sets the value of the sarService property.
     * 
     * @param value
     *     allowed object is
     *     {@link SarServiceType }
     *     
     */
    public void setSARService(SarServiceType value) {
        this.sarService = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link PortType }
     *     
     */
    public PortType getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortType }
     *     
     */
    public void setPort(PortType value) {
        this.port = value;
    }

    /**
     * Gets the value of the portFacility property.
     * 
     * @return
     *     possible object is
     *     {@link PortFacilityType }
     *     
     */
    public PortFacilityType getPortFacility() {
        return portFacility;
    }

    /**
     * Sets the value of the portFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortFacilityType }
     *     
     */
    public void setPortFacility(PortFacilityType value) {
        this.portFacility = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceType }
     *     
     */
    public PlaceType getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceType }
     *     
     */
    public void setPlace(PlaceType value) {
        this.place = value;
    }

    /**
     * Gets the value of the polygon property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonType }
     *     
     */
    public PolygonType getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonType }
     *     
     */
    public void setPolygon(PolygonType value) {
        this.polygon = value;
    }

    /**
     * Gets the value of the dataCentreInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DataCentreInfoType }
     *     
     */
    public DataCentreInfoType getDataCentreInfo() {
        return dataCentreInfo;
    }

    /**
     * Sets the value of the dataCentreInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCentreInfoType }
     *     
     */
    public void setDataCentreInfo(DataCentreInfoType value) {
        this.dataCentreInfo = value;
    }

    /**
     * Gets the value of the asp property.
     * 
     * @return
     *     possible object is
     *     {@link AspType }
     *     
     */
    public AspType getASP() {
        return asp;
    }

    /**
     * Sets the value of the asp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspType }
     *     
     */
    public void setASP(AspType value) {
        this.asp = value;
    }

    /**
     * Gets the value of the lritCoordinator property.
     * 
     * @return
     *     possible object is
     *     {@link LritCoordinatorType }
     *     
     */
    public LritCoordinatorType getLRITCoordinator() {
        return lritCoordinator;
    }

    /**
     * Sets the value of the lritCoordinator property.
     * 
     * @param value
     *     allowed object is
     *     {@link LritCoordinatorType }
     *     
     */
    public void setLRITCoordinator(LritCoordinatorType value) {
        this.lritCoordinator = value;
    }

    /**
     * Gets the value of the xPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPath() {
        return xPath;
    }

    /**
     * Sets the value of the xPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPath(String value) {
        this.xPath = value;
    }

}
