//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sarFacilityTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sarFacilityTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RB"/>
 *     &lt;enumeration value="RV"/>
 *     &lt;enumeration value="SRG"/>
 *     &lt;enumeration value="MRG"/>
 *     &lt;enumeration value="LRG"/>
 *     &lt;enumeration value="VLR"/>
 *     &lt;enumeration value="ELR"/>
 *     &lt;enumeration value="HEL-L"/>
 *     &lt;enumeration value="HEL-M"/>
 *     &lt;enumeration value="HEL-H"/>
 *     &lt;enumeration value="GSU"/>
 *     &lt;enumeration value="MAU"/>
 *     &lt;enumeration value="UIU"/>
 *     &lt;enumeration value="DUIU"/>
 *     &lt;enumeration value="FFU"/>
 *     &lt;enumeration value="IRU"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sarFacilityTypeType")
@XmlEnum
public enum SarFacilityTypeType {

    RB("RB"),
    RV("RV"),
    SRG("SRG"),
    MRG("MRG"),
    LRG("LRG"),
    VLR("VLR"),
    ELR("ELR"),
    @XmlEnumValue("HEL-L")
    HEL_L("HEL-L"),
    @XmlEnumValue("HEL-M")
    HEL_M("HEL-M"),
    @XmlEnumValue("HEL-H")
    HEL_H("HEL-H"),
    GSU("GSU"),
    MAU("MAU"),
    UIU("UIU"),
    DUIU("DUIU"),
    FFU("FFU"),
    IRU("IRU");
    private final String value;

    SarFacilityTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SarFacilityTypeType fromValue(String v) {
        for (SarFacilityTypeType c: SarFacilityTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
