//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sarServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sarServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MMSI" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}mmsiType" minOccurs="0"/>
 *         &lt;element name="CallSign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VHFVoiceCallSign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Telephone" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Telex" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherLandlineComms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvailableFacilities" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}sarFacilityTypeListType" minOccurs="0"/>
 *         &lt;element name="ContactPoint" type="{http://gisis.imo.org/XML/LRIT/ddp/2008}contactPointType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lritID" use="required" type="{http://gisis.imo.org/XML/LRIT/types/2008}sarServiceLRITIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sarServiceType", propOrder = {
    "name",
    "mmsi",
    "callSign",
    "vhfVoiceCallSign",
    "telephone",
    "fax",
    "email",
    "telex",
    "otherLandlineComms",
    "availableFacilities",
    "contactPoint"
})
public class SarServiceType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "MMSI")
    protected String mmsi;
    @XmlElement(name = "CallSign")
    protected String callSign;
    @XmlElement(name = "VHFVoiceCallSign")
    protected String vhfVoiceCallSign;
    @XmlElement(name = "Telephone")
    protected List<String> telephone;
    @XmlElement(name = "Fax")
    protected List<String> fax;
    @XmlElement(name = "Email")
    protected List<String> email;
    @XmlElement(name = "Telex")
    protected List<String> telex;
    @XmlElement(name = "OtherLandlineComms")
    protected String otherLandlineComms;
    @XmlList
    @XmlElement(name = "AvailableFacilities")
    protected List<SarFacilityTypeType> availableFacilities;
    @XmlElement(name = "ContactPoint")
    protected List<ContactPointType> contactPoint;
    @XmlAttribute(required = true)
    protected String lritID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mmsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMSI() {
        return mmsi;
    }

    /**
     * Sets the value of the mmsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMSI(String value) {
        this.mmsi = value;
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    /**
     * Gets the value of the vhfVoiceCallSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVHFVoiceCallSign() {
        return vhfVoiceCallSign;
    }

    /**
     * Sets the value of the vhfVoiceCallSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVHFVoiceCallSign(String value) {
        this.vhfVoiceCallSign = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTelephone() {
        if (telephone == null) {
            telephone = new ArrayList<String>();
        }
        return this.telephone;
    }

    /**
     * Gets the value of the fax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFax() {
        if (fax == null) {
            fax = new ArrayList<String>();
        }
        return this.fax;
    }

    /**
     * Gets the value of the email property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the email property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEmail() {
        if (email == null) {
            email = new ArrayList<String>();
        }
        return this.email;
    }

    /**
     * Gets the value of the telex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTelex() {
        if (telex == null) {
            telex = new ArrayList<String>();
        }
        return this.telex;
    }

    /**
     * Gets the value of the otherLandlineComms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLandlineComms() {
        return otherLandlineComms;
    }

    /**
     * Sets the value of the otherLandlineComms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLandlineComms(String value) {
        this.otherLandlineComms = value;
    }

    /**
     * Gets the value of the availableFacilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableFacilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableFacilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SarFacilityTypeType }
     * 
     * 
     */
    public List<SarFacilityTypeType> getAvailableFacilities() {
        if (availableFacilities == null) {
            availableFacilities = new ArrayList<SarFacilityTypeType>();
        }
        return this.availableFacilities;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactPointType }
     * 
     * 
     */
    public List<ContactPointType> getContactPoint() {
        if (contactPoint == null) {
            contactPoint = new ArrayList<ContactPointType>();
        }
        return this.contactPoint;
    }

    /**
     * Gets the value of the lritID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLritID() {
        return lritID;
    }

    /**
     * Sets the value of the lritID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLritID(String value) {
        this.lritID = value;
    }

}
