//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.ddp._2008;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for territoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="territoryType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://gisis.imo.org/XML/LRIT/ddp/2008}contractingGovernmentType">
 *       &lt;attribute name="contractingGovernmentID" use="required" type="{http://gisis.imo.org/XML/LRIT/types/2008}contractingGovernmentLRITIDType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "territoryType")
public class TerritoryType
    extends ContractingGovernmentType
{

    @XmlAttribute(required = true)
    protected String contractingGovernmentID;

    /**
     * Gets the value of the contractingGovernmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractingGovernmentID() {
        return contractingGovernmentID;
    }

    /**
     * Sets the value of the contractingGovernmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractingGovernmentID(String value) {
        this.contractingGovernmentID = value;
    }

}
