
package org.imo.gisis.xml.lrit._2008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.imo.gisis.xml.lrit.ddpnotification._2008.DDPNotificationType;
import org.imo.gisis.xml.lrit.ddpupdate._2008.DDPUpdateType;
import org.imo.gisis.xml.lrit.positionreport._2008.ShipPositionReportType;
import org.imo.gisis.xml.lrit.positionrequest._2008.ShipPositionRequestType;
import org.imo.gisis.xml.lrit.pricingnotification._2008.PricingNotificationType;
import org.imo.gisis.xml.lrit.pricingupdate._2008.PricingUpdateType;
import org.imo.gisis.xml.lrit.receipt._2008.ReceiptType;
import org.imo.gisis.xml.lrit.sarsurpicrequest._2008.SARSURPICType;
import org.imo.gisis.xml.lrit.systemstatus._2008.SystemStatusType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dcPortType", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.imo.gisis.xml.lrit.types._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.positionreport._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.pricingnotification._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.sarsurpicrequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.systemstatus._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.pricingupdate._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.ddprequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.receipt._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.ddpupdate._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.positionrequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.ddpnotification._2008.ObjectFactory.class
})
public interface DcPortType {


    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "ShipPositionReport")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response shipPositionReport(
        @WebParam(name = "ShipPositionReport", targetNamespace = "http://gisis.imo.org/XML/LRIT/positionReport/2008", partName = "params")
        ShipPositionReportType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "ShipPositionRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response shipPositionRequest(
        @WebParam(name = "ShipPositionRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/positionRequest/2008", partName = "params")
        ShipPositionRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "SARSURPICRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response sarsurpicRequest(
        @WebParam(name = "SARSURPICRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008", partName = "params")
        SARSURPICType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "Receipt")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response receipt(
        @WebParam(name = "Receipt", targetNamespace = "http://gisis.imo.org/XML/LRIT/receipt/2008", partName = "params")
        ReceiptType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "DDPNotification")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response ddpNotification(
        @WebParam(name = "DDPNotification", targetNamespace = "http://gisis.imo.org/XML/LRIT/ddpNotification/2008", partName = "params")
        DDPNotificationType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "DDPUpdate")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response ddpUpdate(
        @WebParam(name = "DDPUpdate", targetNamespace = "http://gisis.imo.org/XML/LRIT/ddpUpdate/2008", partName = "params")
        DDPUpdateType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "SystemStatus")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response systemStatus(
        @WebParam(name = "SystemStatus", targetNamespace = "http://gisis.imo.org/XML/LRIT/systemStatus/2008", partName = "params")
        SystemStatusType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "PricingNotification")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response pricingNotification(
        @WebParam(name = "PricingNotification", targetNamespace = "http://gisis.imo.org/XML/LRIT/pricingNotification/2008", partName = "params")
        PricingNotificationType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "PricingUpdate")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response pricingUpdate(
        @WebParam(name = "PricingUpdate", targetNamespace = "http://gisis.imo.org/XML/LRIT/pricingUpdate/2008", partName = "params")
        PricingUpdateType params);

}
