
package org.imo.gisis.xml.lrit._2008;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ideDDPService", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", wsdlLocation = "http://localhost:8080/ide_ddp")
public class IdeDDPService
    extends Service
{

    private final static URL IDEDDPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.imo.gisis.xml.lrit._2008.IdeDDPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.imo.gisis.xml.lrit._2008.IdeDDPService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ide_ddp");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ide_ddp', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IDEDDPSERVICE_WSDL_LOCATION = url;
    }

    public IdeDDPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdeDDPService() {
        super(IDEDDPSERVICE_WSDL_LOCATION, new QName("http://gisis.imo.org/XML/LRIT/2008", "ideDDPService"));
    }

    /**
     * 
     * @return
     *     returns IdeDDPPortType
     */
    @WebEndpoint(name = "ideDDPPort")
    public IdeDDPPortType getIdeDDPPort() {
        return super.getPort(new QName("http://gisis.imo.org/XML/LRIT/2008", "ideDDPPort"), IdeDDPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdeDDPPortType
     */
    @WebEndpoint(name = "ideDDPPort")
    public IdeDDPPortType getIdeDDPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gisis.imo.org/XML/LRIT/2008", "ideDDPPort"), IdeDDPPortType.class, features);
    }

}
