
package org.imo.gisis.xml.lrit._2008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.imo.gisis.xml.lrit.ddprequest._2008.DDPRequestType;
import org.imo.gisis.xml.lrit.receipt._2008.ReceiptType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2_01-hudson-189-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ddpPortType", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.imo.gisis.xml.lrit.receipt._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.ddprequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.types._2008.ObjectFactory.class
})
public interface DdpPortType {


    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "DDPRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response ddpRequest(
        @WebParam(name = "DDPRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/ddpRequest/2008", partName = "params")
        DDPRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "Receipt")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response receipt(
        @WebParam(name = "Receipt", targetNamespace = "http://gisis.imo.org/XML/LRIT/receipt/2008", partName = "params")
        ReceiptType params);

}
