
package org.imo.gisis.xml.lrit._2008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.imo.gisis.xml.lrit.journalreport._2008.JournalReportType;
import org.imo.gisis.xml.lrit.positionreport._2008.ShipPositionReportType;
import org.imo.gisis.xml.lrit.positionrequest._2008.ShipPositionRequestType;
import org.imo.gisis.xml.lrit.pricingrequest._2008.PricingRequestType;
import org.imo.gisis.xml.lrit.pricingupdate._2008.PricingUpdateType;
import org.imo.gisis.xml.lrit.receipt._2008.ReceiptType;
import org.imo.gisis.xml.lrit.sarsurpicrequest._2008.SARSURPICType;
import org.imo.gisis.xml.lrit.systemstatus._2008.SystemStatusType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2_01-hudson-189-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "idePortType", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.imo.gisis.xml.lrit.systemstatus._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.pricingupdate._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.positionrequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.journalreport._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.sarsurpicrequest._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.positionreport._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.types._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.receipt._2008.ObjectFactory.class,
    org.imo.gisis.xml.lrit.pricingrequest._2008.ObjectFactory.class
})
public interface IdePortType {


    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "ShipPositionReport")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response shipPositionReport(
        @WebParam(name = "ShipPositionReport", targetNamespace = "http://gisis.imo.org/XML/LRIT/positionReport/2008", partName = "params")
        ShipPositionReportType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "ShipPositionRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response shipPositionRequest(
        @WebParam(name = "ShipPositionRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/positionRequest/2008", partName = "params")
        ShipPositionRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "SARSURPICRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response sarsurpicRequest(
        @WebParam(name = "SARSURPICRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/sarSurpicRequest/2008", partName = "params")
        SARSURPICType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "Receipt")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response receipt(
        @WebParam(name = "Receipt", targetNamespace = "http://gisis.imo.org/XML/LRIT/receipt/2008", partName = "params")
        ReceiptType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "SystemStatus")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response systemStatus(
        @WebParam(name = "SystemStatus", targetNamespace = "http://gisis.imo.org/XML/LRIT/systemStatus/2008", partName = "params")
        SystemStatusType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "JournalReport")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response journalReport(
        @WebParam(name = "JournalReport", targetNamespace = "http://gisis.imo.org/XML/LRIT/journalReport/2008", partName = "params")
        JournalReportType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "PricingRequest")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response pricingRequest(
        @WebParam(name = "PricingRequest", targetNamespace = "http://gisis.imo.org/XML/LRIT/pricingRequest/2008", partName = "params")
        PricingRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns org.imo.gisis.xml.lrit._2008.Response
     */
    @WebMethod(operationName = "PricingUpdate")
    @WebResult(name = "Response", targetNamespace = "http://gisis.imo.org/XML/LRIT/2008", partName = "params")
    public Response pricingUpdate(
        @WebParam(name = "PricingUpdate", targetNamespace = "http://gisis.imo.org/XML/LRIT/pricingUpdate/2008", partName = "params")
        PricingUpdateType params);

}
