//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//


package org.imo.gisis.xml.lrit.pricingfile._2008;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imo.gisis.xml.lrit.pricingfile._2008 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imo.gisis.xml.lrit.pricingfile._2008
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PricingFile.PriceList }
     * 
     */
    public PricingFile.PriceList createPricingFilePriceList() {
        return new PricingFile.PriceList();
    }

    /**
     * Create an instance of {@link PricingFile.PriceList.BreakDown }
     * 
     */
    public PricingFile.PriceList.BreakDown createPricingFilePriceListBreakDown() {
        return new PricingFile.PriceList.BreakDown();
    }

    /**
     * Create an instance of {@link PricingFile }
     * 
     */
    public PricingFile createPricingFile() {
        return new PricingFile();
    }

}
