//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.02 at 02:31:37 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gisis.imo.org/XML/LRIT/pricingFile/2008", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.imo.gisis.xml.lrit.pricingfile._2008;
